version: "3.8"
services:
  redis:
    build: ./redis
    ports:
      - "6379:6379"
    env_file:
      - "./env/redis.env"
    container_name: redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6379"]
      interval: 10s
      timeout: 10s
      retries: 5
  security:
    build: ./backend/security
    ports:
      - "7080:7080"
    volumes:
      - uploads:/app/uploads
    env_file:
      - "./env/security.env"
    container_name: security
    restart: on-failure
    depends_on:
      - redis
  general:
    build: ./backend/general
    ports:
      - "8080:8080"
    env_file:
      - "./env/general.env"
    container_name: general
    restart: on-failure
    depends_on:
      - redis
  chat:
    build: ./backend/chat
    ports:
      - "9080:9080"
    env_file:
      - "./env/chat.env"
    container_name: chat
    restart: on-failure
    depends_on:
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - "./env/frontend.env"
    container_name: frontend
    restart: on-failure
    depends_on:
      - security
      - general
      - chat

volumes:
  uploads:
