apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: adamchiu0214/message-board-chat
          env:
            - name: MYSQL_IP
              value: "mysql-service.default:3306"
            - name: REDIS_IP
              value: "redis-service.default:6379"
            - name: MONGO_IP
              value: "mongodb-service.default:27017"
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: chat-env
                  key: mysql-password
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: chat-env
                  key: redis-password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: chat-env
                  key: mongo-database
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: chat-env
                  key: mongo-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: chat-env
                  key: mongo-password
            - name: JWT_HS256_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: chat-env
                  key: jwt-key
