apiVersion: v1
kind: Service
metadata:
  name: general-service
spec:
  selector:
    app: general
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: general-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: general
  template:
    metadata:
      labels:
        app: general
    spec:
      containers:
        - name: general
          image: adamchiu0214/message-board-general
          env:
            - name: MYSQL_IP
              value: "mysql-service.default:3306"
            - name: REDIS_IP
              value: "redis-service.default:6379"
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: general-env
                  key: mysql-password
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: general-env
                  key: redis-password
            - name: JWT_HS256_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: general-env
                  key: jwt-key
