apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    data: mongodb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      data: mongodb
  template:
    metadata:
      labels:
        data: mongodb
    spec:
      containers:
        - name: mongodb
          image: adamchiu0214/message-board-mongodb
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-env
                  key: mongo-database
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-env
                  key: mongo-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mongodb-env
                  key: mongo-password
