apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    data: mysql
  # type: ClusterIP
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      data: mysql
  template:
    metadata:
      labels:
        data: mysql
    spec:
      containers:
        - name: mysql
          image: adamchiu0214/message-board-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-env
                  key: mysql-password
