apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    data: redis
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      data: redis
  template:
    metadata:
      labels:
        data: redis
    spec:
      containers:
        - name: redis
          image: adamchiu0214/message-board-redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: redis-env
                  key: redis-password
