apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  selector:
    app: security
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7080
      targetPort: 7080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
        - name: security
          image: adamchiu0214/message-board-security:latest
          env:
            - name: MYSQL_IP
              value: "mysql-service.default:3306"
            - name: REDIS_IP
              value: "redis-service.default:6379"
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: security-env
                  key: mysql-password
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: security-env
                  key: redis-password
            - name: ADMIN_MAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: security-env
                  key: admin-mail-address
            - name: ADMIN_MAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: security-env
                  key: admin-mail-password
            - name: JWT_HS256_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: security-env
                  key: jwt-key
          volumeMounts:
            - mountPath: /app/uploads
              name: image-volume
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: host-pvc
